### PR TITLE
#1 Added info.md

### PR DESCRIPTION
**Pull request by svrks-boop**
Issue: #1 

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by bhupesh98** [comment]
@svrks-boop Do folow the PR template and change the files accordingly, atleast add you name, college and something like that

**Comment by svrks-boop** [comment]
@bhupesh98 PTAL

**Comment by saiushasree1** [comment]
Hey there!in PR  should be like issue: #1 not issue: #ISSUENUMBER.

**Comment by svrks-boop** [comment]
done!

**Pull request merged**
